[package]
name = "tournament"
version = "0.1.0"
authors = ["Cameron Bowie <bowiec@onid.oregonstate.edu>"]

[dependencies]
toml = "0.1"

[dependencies.pokedex]
path = "../pokedex"

[dependencies.battle_sim]
path = "../battle_sim"
